/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface OperatorRow {
  'defectType' : string,
  'operationName' : string,
  'defectCounts' : Array<bigint>,
  'operatorName' : string,
  'numberOfDefects' : bigint,
  'photo' : [] | [PhotoData],
  'actionTaken' : string,
}
export interface PhotoData { 'imageData' : string, 'timestamp' : bigint }
export interface QCReport {
  'id' : bigint,
  'title' : string,
  'date' : bigint,
  'submittedTimestamp' : bigint,
  'operatorRows' : Array<OperatorRow>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearDraftReport' : ActorMethod<[], undefined>,
  'deleteReport' : ActorMethod<[bigint], undefined>,
  'getAllReports' : ActorMethod<[], Array<QCReport>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDraftReport' : ActorMethod<[], [] | [QCReport]>,
  'getReportById' : ActorMethod<[bigint], [] | [QCReport]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDraftReport' : ActorMethod<
    [string, bigint, Array<OperatorRow>],
    undefined
  >,
  'saveReport' : ActorMethod<[string, bigint, Array<OperatorRow>], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];